from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^inscripcion-curso/(?P<slug>(\w|-)+)/$',
        'billing.views.inscription_course',
        name='url_inscription_course'),
    url(r'^$', 'courses.views.courses_home', name='courses_home'),
    url(r'^inscripcion-curso/$',
        'billing.views.inscription_course',
        name='url_inscription_course_default'),
    url(r'^api/crear-simulacro/$', 'courses.views.ukanbook_create',
        name='urlukanbook_create_simulation'),
    url(r'^estudiante-clases/?$',
        'courses.views.get_class_student',
        name='urlstudentclass'),
    url(r'^clases-en-vivo/?$', 'courses.views.course_live',
        name='course_live'),
    url(r'^live/(?P<id>(\w|-)+)/$', 'courses.views.course_classroom',
        name='couse_room_url'),
    url(r'^discusiones/?$', 'courses.views.course_discussions',
        name='course_discussions'),
    url(r'^estudiante-vista-simulacro/?$',
        'courses.views.student_view_simulacrum',
        name='url_student_view_simulacrum'),
    url(r'^recursos/?$', 'courses.views.course_resources',
        name='course_resources'),
    url(r'^recursos/(?P<slug>(\w|-)+)/$', 'courses.views.course_resources',
        name='resource'),
    url(r'^reportes/?$', 'courses.views.course_reports',
        name='course_reports'),
    url(r'^get_messages/?$', 'courses.views.get_messages',
        name='get_course_messages'),
    url(r'^create_message/?$', 'courses.views.create_message',
        name='create_course_message'),
    url(r'^update_student_school_course/?$', 'courses.views.update_student_school_course',
    name='update_student_school_course'),
    url(r'^mark_resource/?$', 'courses.views.mark_resource_as_viewed',
        name='mark_resource'),
    url(r'^studiante-clase-vista/?$', 'courses.views.student_view_class',
        name='url_student_view_class'),
    url(r'^payment_test/?$', 'courses.views.course_payment_test',
        name='payment_test'),
    url(r'^reportar-clase-tutor/?$', 'courses.views.tutor_report_class',
        name='url_report_class_tutor'),
    url(r'^calificar-clase/?$', 'courses.views.grade_class',
        name='url_grade_class'),
    url(r'^get_reportclasstutor_json/$',
        'courses.views.get_reportclasstutor_json',
        name='get_reportclasstutor_json'),

)
